name: builder

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest,self-hosted]
    runs-on: ${{ matrix.os }}
    env:
      app_name: files_${{ matrix.os}}

    steps:
    - name: print matrix env
      run: ls ~
      
    - uses: actions/checkout@v3
    - name: build
      uses: actions/setup-java@v3
      with:
        name: app
        path: ${{ env.app_name }}
        retention-days: 3
        
